// <auto-generated />
namespace MyStore.App.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddExternalUserInformation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExternalUserInformation));
        
        string IMigrationMetadata.Id
        {
            get { return "201602220209520_AddExternalUserInformation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
