//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.App.Models.MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad_Sliders
    {
        public int slider_id { get; set; }
        public string slider_title { get; set; }
        public string slider_desc { get; set; }
        public string slider_link { get; set; }
        public bool slider_active { get; set; }
        public string slider_main_img { get; set; }
        public string slider_sub_img { get; set; }
        public Nullable<byte> slider_order_num { get; set; }
    }
}
