//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.App.Models.MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog_Actors
    {
        public Blog_Actors()
        {
            this.Blogs = new HashSet<Blog>();
        }
    
        public int actor_id { get; set; }
        public string actor_image { get; set; }
        public string actor_description { get; set; }
        public string actor_name { get; set; }
    
        public virtual ICollection<Blog> Blogs { get; set; }
    }
}
