//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.App.Models.MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Items
    {
        public int cart_item_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<System.Guid> cart_id { get; set; }
        public Nullable<double> cart_item_quantity { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
