//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.App.Models.MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Product_Type
    {
        public Ref_Product_Type()
        {
            this.Products = new HashSet<Product>();
            this.Child_Product_Types = new HashSet<Ref_Product_Type>();
        }
    
        public int product_type_id { get; set; }
        public Nullable<int> parent_product_type_id { get; set; }
        public string product_type_description_vn { get; set; }
        public string product_type_description_en { get; set; }
        public bool is_active { get; set; }
        public byte product_type_order { get; set; }
        public string product_type_code { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Ref_Product_Type> Child_Product_Types { get; set; }
        public virtual Ref_Product_Type Parent_Product_Type { get; set; }
    }
}
