//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.App.Models.MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping_Bills
    {
        public Shipping_Bills()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int shipping_id { get; set; }
        public string shipping_code { get; set; }
        public System.DateTime shipping_date { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
