//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.App.Models.MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Advices
    {
        public int advise_id { get; set; }
        public string user_name { get; set; }
        public string user_mail { get; set; }
        public string advise_subject { get; set; }
        public string advise_body { get; set; }
    }
}
